package me.darknet.dex.convert.ir.optimize;

import me.darknet.dex.convert.ConversionResult;
import me.darknet.dex.convert.Converters;
import me.darknet.dex.convert.util.Decompile;
import me.darknet.dex.tree.DexFile;
import me.darknet.dex.tree.definitions.ClassDefinition;
import me.darknet.dex.tree.definitions.InnerClass;
import me.darknet.dex.util.TestUtils;
import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Opcodes;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for reconstructing patterns in the IR that are commonly generated by Java decompilers, but may be obfuscated in the original dex code.
 */
class IrReconstructPatternTest {
	/**
	 * CFR decompiler expects anonymous inner classes to not specify the 'outer class' in the InnerClass attribute.
	 * So for testing we'll assign it this dummy value when it is null (Mainly because IJ non-null agent gets mad otherwise).
	 */
	private static final String ANON_OUTER = "ThisIsAnonymousSoWeDontEmitOuterClassToMakeDecompilerPatternMatcherHappy";

	@Test
	void enumSugar() {
		// Main has an inner class:
		//  public enum Shubbery { GROUND, CRAWLING, HANGING }
		ClassDefinition enumDef = TestUtils.getDexDefinition("035-enum", "Main$Shubbery");

		// Decompile the enum and verify that it looks like a normal Java enum declaration
		// and not some mess of static fields and methods.
		byte[] javaClass = Converters.IR.toJavaClass(enumDef);
		String decomp = Decompile.decompile("Main$Shubbery", javaClass);
		assertTrue(decomp.matches("[\\s\\S]+enum\\s\\S+\\s\\{\\s+GROUND,\\s+CRAWLING,\\s+HANGING;\\s+}\\s*"));
	}

	@Test
	void stringBuilder() {
		// Main has a string concat:
		//  System.out.print("Starting thread '" + t.getName() + "'\n");
		ClassDefinition classDef = TestUtils.getDexDefinition("039-join-main", "Main");

		// Decompile the class and verify that the string concat is emitted in such a way that
		// the decompiler can pattern-match it and reconstruct it as a normal Java string concat expression.
		// We shouldn't see any explicit StringBuilder usage in the decompiled code.
		byte[] javaClass = Converters.IR.toJavaClass(classDef);
		String decomp = Decompile.decompile("Main", javaClass);
		assertFalse(decomp.contains("new StringBuilder"), "Expected StringBuilder usage to be pattern-matched away by decompiler");
		assertFalse(decomp.contains(".append("), "Expected StringBuilder usage to be pattern-matched away by decompiler");
		assertTrue(decomp.matches("(?s).*\"Starting thread '\" \\+ \\w+\\.getName\\(\\) \\+ \"'\\\\n\".*"));
	}

	@Test
	void emptyInnerAnonymousClassWithNoSupportingAnnotation() {
		// Main's source has an anonymous inner class:
		//    private static Runnable theRunnable = new Runnable() {
		//       public void run() {}
		//    };
		//
		//    private static Runnable create() {
		//        return new Runnable() {
		//            public void run() {}
		//        };
		//    }
		DexFile file = TestUtils.getDexFile("085-old-style-inner-class");
		ConversionResult result = Converters.IR.toClasses(file);
		assertTrue(result.errors().isEmpty(), () -> "Unexpected conversion errors: " + result.errors());

		// Assert first anonymous inner class metadata is reconstructed.
		ClassMetadata firstAnonymous = readClassMetadata(result.classes().get("Main$1"));
		assertEquals("Main", firstAnonymous.outerOwner());
		assertNull(firstAnonymous.outerMethodName());
		assertTrue(firstAnonymous.innerClasses().stream()
				.anyMatch(inner -> "Main$1".equals(inner.innerClassName()) && ANON_OUTER.equals(inner.outerClassName())));

		// Assert second anonymous inner class metadata is reconstructed.
		// This one should also have outer method metadata since it's created inside a method.
		ClassMetadata secondAnonymous = readClassMetadata(result.classes().get("Main$2"));
		assertEquals("Main", secondAnonymous.outerOwner());
		assertEquals("create", secondAnonymous.outerMethodName());
		assertEquals("()Ljava/lang/Runnable;", secondAnonymous.outerMethodDesc());
		assertTrue(secondAnonymous.innerClasses().stream()
				.anyMatch(inner -> "Main$2".equals(inner.innerClassName()) && ANON_OUTER.equals(inner.outerClassName())));

		// Decompile the classes and verify the anonymous inner classes are reconstructed inline as anonymous classes
		// and not emitted as separate named inner classes with synthetic names.
		Map<String, byte[]> classes = result.classes();
		String decomp = Decompile.decompile("Main", classes);
		assertFalse(decomp.contains("class Main$1"), "Anonymous class should be reconstructed inline");
		assertFalse(decomp.contains("class Main$2"), "Anonymous class should be reconstructed inline");
		assertTrue(decomp.contains("static Runnable theRunnable = new Runnable(){"));
		assertTrue(decomp.contains("Runnable runnable = new Runnable(){") && decomp.contains("return runnable;"));
	}

	@Test
	void namedInnerClassFixtureRemainsStable() {
		DexFile file = TestUtils.getDexFile("038-inner-null");
		ConversionResult result = Converters.IR.toClasses(file);
		assertTrue(result.errors().isEmpty(), () -> "Unexpected conversion errors: " + result.errors());

		ClassMetadata special = readClassMetadata(result.classes().get("Main$Special"));
		assertEquals("Main", special.outerOwner());
		assertTrue(special.innerClasses().stream()
				.anyMatch(inner -> "Main$Special".equals(inner.innerClassName()) && "Special".equals(inner.innerName())));

		String decomp = Decompile.decompile("Main", result.classes());
		String normalized = decomp.replaceAll("\\s+", " ");
		assertFalse(normalized.contains("Main$Special"), "Named inner classes should not leak the raw '$' binary name into decompilation");
		assertTrue(normalized.matches(".*new (Main\\.)?Special\\(\\).*"), "Expected named inner class construction to remain readable");
	}

	private static @NotNull ClassMetadata readClassMetadata(byte[] bytecode) {
		assertNotNull(bytecode, "Expected class bytecode to be present");
		String[] outerOwner = new String[1];
		String[] outerMethodName = new String[1];
		String[] outerMethodDesc = new String[1];
		List<InnerClass> innerClasses = new ArrayList<>();
		new ClassReader(bytecode).accept(new ClassVisitor(Opcodes.ASM9) {
			@Override
			public void visitOuterClass(String owner, String name, String descriptor) {
				outerOwner[0] = owner;
				outerMethodName[0] = name;
				outerMethodDesc[0] = descriptor;
			}

			@Override
			public void visitInnerClass(String name, String outerName, String innerName, int access) {
				innerClasses.add(new InnerClass(name, outerName == null ? ANON_OUTER : outerName, innerName, access));
			}
		}, 0);
		return new ClassMetadata(outerOwner[0], outerMethodName[0], outerMethodDesc[0], List.copyOf(innerClasses));
	}

	private record ClassMetadata(String outerOwner,
	                             String outerMethodName,
	                             String outerMethodDesc,
	                             List<InnerClass> innerClasses) {
	}
}
